#pragma once

#ifndef COMMON_H
#define COMMON_H

#include <QString>

const QChar separator(';');

QString& operator<< (QString& m, const QString& s);


enum PolynomMode {
    REAL_MODE = 0,
    COMPLEX_MODE = 1
};


enum messages {
    CREATE_POLYNOMIAL_REQUEST,
    CREATE_POLYNOMIAL_ANSWER,
    CALCULATE_VALUE_REQUEST,
    CALCULATE_VALUE_ANSWER,
    CHANGE_LEADING_COEFF_REQUEST,
    CHANGE_LEADING_COEFF_ANSWER,
    RESIZE_POLYNOMIAL_REQUEST,
    RESIZE_POLYNOMIAL_ANSWER,
    CHANGE_ROOT_REQUEST,
    CHANGE_ROOT_ANSWER,
    SHOW_FACTOR_FORM_REQUEST,
    SHOW_STANDARD_FORM_REQUEST,
    SHOW_POLYNOMIAL_ANSWER,
    RESET_POLYNOMIAL_REQUEST,
    RESET_POLYNOMIAL_ANSWER,
    ERROR_ANSWER
};

#endif // COMMON_H
